// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID           string         `json:"id"`
	Pseudonym    string         `json:"pseudonym"`
	Email        string         `json:"email"`
	Password     string         `json:"password"`
	Avatar       sql.NullString `json:"avatar"`
	CreatedAt    time.Time      `json:"created_at"`
	LastActiveAt time.Time      `json:"last_active_at"`
}
