// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id,
  pseudonym,
  email,
  password,
  avatar
) VALUES ( ?, ?, ?, ?, ? )
RETURNING id, pseudonym, email, password, avatar, created_at, last_active_at
`

type CreateUserParams struct {
	ID        string         `json:"id"`
	Pseudonym string         `json:"pseudonym"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Avatar    sql.NullString `json:"avatar"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Pseudonym,
		arg.Email,
		arg.Password,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Pseudonym,
		&i.Email,
		&i.Password,
		&i.Avatar,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}
