// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id,
  pseudonym,
  email,
  password,
  avatar
) VALUES ( ?, ?, ?, ?, ? )
RETURNING id, pseudonym, email, password, avatar, created_at, last_active_at
`

type CreateUserParams struct {
	ID        string         `json:"id"`
	Pseudonym string         `json:"pseudonym"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Avatar    sql.NullString `json:"avatar"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Pseudonym,
		arg.Email,
		arg.Password,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Pseudonym,
		&i.Email,
		&i.Password,
		&i.Avatar,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, pseudonym, avatar FROM users
WHERE id = ? LIMIT 1
`

type GetUserRow struct {
	ID        string         `json:"id"`
	Pseudonym string         `json:"pseudonym"`
	Avatar    sql.NullString `json:"avatar"`
}

func (q *Queries) GetUser(ctx context.Context, id string) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(&i.ID, &i.Pseudonym, &i.Avatar)
	return i, err
}

const listUser = `-- name: ListUser :many
SELECT id, pseudonym, avatar FROM users
ORDER BY id
LIMIT ? OFFSET ?
`

type ListUserParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListUserRow struct {
	ID        string         `json:"id"`
	Pseudonym string         `json:"pseudonym"`
	Avatar    sql.NullString `json:"avatar"`
}

func (q *Queries) ListUser(ctx context.Context, arg ListUserParams) ([]ListUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRow{}
	for rows.Next() {
		var i ListUserRow
		if err := rows.Scan(&i.ID, &i.Pseudonym, &i.Avatar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = ?,
password = ?,
avatar = ?
WHERE id = ?
RETURNING id, pseudonym, email, password, avatar, created_at, last_active_at
`

type UpdateUserParams struct {
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Avatar   sql.NullString `json:"avatar"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Email,
		arg.Password,
		arg.Avatar,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Pseudonym,
		&i.Email,
		&i.Password,
		&i.Avatar,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}
